name: Gerar Animação da Cobrinha

on:
  schedule:
    - cron: "0 6 * * *"  
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
   
      - name: Checkout
        uses: actions/checkout@v3


      - name: Definir variável de usuário
        run: |
          echo "GITHUB_USER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)" >> $GITHUB_ENV

    
      - name: Gerar a animação da cobrinha
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ env.GITHUB_USER }}
          outputs: dist/cobrinha.svg

  
      - name: Publicar a animação
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
